name: help_connect
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_storage: ^12.4.4
  firebase_messaging: ^15.2.4
  google_maps_flutter: ^2.12.1
  provider: ^6.1.4
  fluttertoast: ^8.2.12
  flutter_bloc: ^9.1.1
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.2.1
  intl: ^0.20.2
  rxdart: ^0.28.0

  user_repository:
    path: D:/help_connect/packages/user_repository
  activity_repository:
    path: D:/help_connect/packages/activity_repository
  business_repository:
    path: D:/help_connect/packages/business_repository

  share_plus: ^11.0.0
  image_picker: ^1.1.2

  url_launcher: ^6.3.1
  badges: ^3.1.2
  shared_preferences: ^2.5.3
  http: ^1.4.0
  cloud_functions: ^5.4.0
  flutter_cache_manager: ^3.4.1
  geolocator: ^14.0.0
  geocoding: ^3.0.0
  location: ^8.0.0
  dropdown_button2: ^2.3.9
  flutter_svg: ^2.1.0
  fl_chart: ^0.71.0
  cached_network_image: ^3.4.1
  async: ^2.12.0
  flutter_facebook_auth: ^7.1.2
  flutter_fireworks: ^1.0.8

  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  axios_package: ^0.0.3
  flutter_dotenv: ^5.2.1
#  momo_vn: ^2.0.2
  uni_links: ^0.5.1
  firebase_dynamic_links: ^6.1.6
  easy_localization: ^3.0.7+1
  google_fonts: ^6.2.1
  flutter_slidable: ^4.0.0
  pdf: ^3.11.3
  printing: ^5.14.2
  path_provider: ^2.1.5
  permission_handler: ^12.0.0+1
  excel: ^4.0.6
  firebase_app_check: ^0.3.2+6
  open_file: ^3.5.10
  diacritic: ^0.1.6
  google_generative_ai: ^0.4.7
  web_socket_channel: ^3.0.3
  universal_platform: ^1.1.0
  google_mlkit_face_detection: ^0.13.1
  string_similarity: ^2.1.1
  google_mlkit_text_recognition: ^0.15.0
  google_mlkit_commons: ^0.11.0
  connectivity_plus: ^6.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
    - .env
    - assets/translations/